### ISSUE TITLE
Missing License Disallows Use

### ISSUE THREAD

**Issue by l-zeuch** [Crenshaw7860/Yagpdb-ccs#7]
Hello there!

Super cool custom commands, however due to the missing license they're subject to **exclusive copyright**, which *technically* disallows other users to use your custom commands, more reading on that [here](https://choosealicense.com/no-permission/ "what happens with no license?").

I used [this tool](https://choosealicense.com/ "choose a license") to find one suiting for me; I for myself use the [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause "BSD-3-Clause"), as it is quite permissive, whilst, as usual, requiring proper credit, the disclaimer, and, opposed to the BSD-2-Clause, also disallowing usage of your and contributor's names to endorse or promote derivative work without prior, explicitly written permission.

You can, of course, pick a different license or write your own. But please, please, pick a license.

Kind regards!

**Comment by Crenshaw1312** [comment]
presto GPLv3, idk I use it often so, for now it's good
